apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-1
spec:
  containers:
    - name: priv-container
      image: nicolaka/netshoot
      command:
        - sleep
        - 9999s
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-2
spec:
  containers:
    - name: priv-container
      image: nicolaka/netshoot
      command:
        - sleep
        - 9999s
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]