
apiVersion: v1
kind: Service
metadata:
  name: demo-kubecon
spec:
  type: ClusterIP
  ports:
  - port: 8100
    targetPort: 80
  selector:
    app: demo-kubecon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubecon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-kubecon
  template:
    metadata:
      labels:
        app: demo-kubecon
    spec:
      containers:
      - name: demo-kubecon-container
        image: zanetworker/demo-webserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]