---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkTrafficShaper
metadata:
  name: inject-delay
spec:
  targets:
    - kind: selector
      namespace: default
      targetSelector:
        matchLabels:
          app: demo-kubecon
      configuration:
        type: delay
        device: eth0
        value: 200ms
