---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkConnectivityTest
metadata:
  name: port-test
spec:
  layer: "4"
  source:
    name: "kube-apiserver-kind-kubecon2019-control-plane"
    namespace: "kube-system"
    container: ""
  destinations:
    - kind: service
      namespace: default
      name: demo-kubecon
      port: "8100"
